project:
  type: website

website:
  title: "IS415-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DataWrangling.qmd
        text: Data Wrangling
      - href: poster.qmd
        text: Poster


format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

