project:
  type: website

website:
  title: "IS415-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DataWrangling.qmd
        text: Data Wrangling
      - href: poster.qmd
        text: Poster
      - href: guide.qmd
        text: User Guide
      - href: https://is415-kwee-cheng.shinyapps.io/G1T9-AbangSmith/
        text: Shiny Application


format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

